const POSITION = {
    AUTO: 0,
    BACK: 1,
    LEFT: 2,
    RIGHT: 3
};

const COLOR = {
    STROKE: "#000",
    DARK: "#444",
    LIGHT: "#eee",
    AQUA_BLUE: "#15EAFD",
    HOT_PINK: "#FF69B4",
    APPLE_GREEN: "#C7FF05"
};

const HARDWARE = {
    KNOB_DIAMETER: 22.4
};

const ENCLOSURE = {
    GUTTER: 5,
    RELATED_GUTTER: 2
};

const KEY = {
    WIDTH: 14.24,
    HEIGHT: 45.72,
    ACCIDENTAL_WIDTH: 7.62,
    ACCIDENTAL_HEIGHT: 22.86
};

const LABEL = {
    HEIGHT: 5
};

const CONTROL = {
    MINIMUM_HEIGHT:
        HARDWARE.KNOB_DIAMETER + ENCLOSURE.RELATED_GUTTER + LABEL.HEIGHT
};

export { COLOR, CONTROL, ENCLOSURE, HARDWARE, KEY, LABEL, POSITION };
